server:
  #服务端口
  port: 8624
  #域名证书
#  ssl:
#    key-store: classpath:anchwngb.cn.pfx
#    key-store-password: XXXXXXX
#    key-store-type: PKCS12

#代理ip
broker:
  ip:
  port: 7890

# 微信小程序配置
we-chat:
  #小程序 ID
  appId:
  #小程序 密钥
  secret:

# Open配置
open:
  # Key池
  keys:
    - 'sk-XXXXXXXXXXXXxXX'
    - 'sk-XXXXXXXXXXXXxXX'
    - 'sk-XXXXXXXXXXxxxxx'

  thirdPartyKey: 'Xxxxxxx'

  choose: true

  isStream: true

  isRandom: false

# bing机器人请求路径
bingUrl: "http://xxxxxx:3000/bing"